<div class="heading">Biography</div>
<div id="biography"><p>Pianist Sean Chen is being hailed as a rising star with a "million-volt smile" and a "formidable set of fingers" (Dallas Morning News). In 2013 Chen won the American Pianists Association's DeHaan Classical Fellowship, one of the most lucrative and significant prizes available to an American pianist; he also won Third Prize at the 14th Van Cliburn International Piano Competition, becoming the first American to reach the finals since 1997. He received Second Prize at the 2011 Seoul International Music Competition, Third Prize at the 2013 Morocco Philharmony International Piano Competition, Best Performance of an American Work at the 2009 Cleveland International Piano Competition, and he was a semifinalist at the 2012 Leeds International Piano Competition.</p>
<p>The 24-year-old American pianist has appeared as soloist with the Indianapolis Symphony Orchestra under Gerard Schwarz, Fort Worth Symphony Orchestra under Leonard Slatkin, Indianapolis Chamber Orchestra, Suwon City Philharmonic, New West Symphony, and the Juilliard Orchestra. He has performed solo recitals under the auspices of the McGraw-Hill Company, New Mexico Symphony Orchestra, New West Symphony, National Chopin Foundation, Scriabin Society, Ventura Music Festival, and the Young Artist Guild of the Music Teachers Association of California. He has performed new works by Lisa Bielawa, Michael Williams, Nicco Athens, Michael Gilbertson, and Reinaldo Moya, among others. Upcoming CD releases include an album of Michael Williams's solo piano works on the Parma label, live recordings from the Cliburn competition, and a solo recording on the Steinway label as part of his American Pianists Association prize.</p>
<p>Born in 1988 in Margate, FL, Chen grew up in the Los Angeles area of Oak Park, CA. His impressive achievements before college included receiving an NFAA ARTSweek award, a prize at the California International Young Artist Competition, the Los Angeles Music Center's Spotlight Award, the Evelyn Bonar Storrs Scholarship, and the Glenn Miller Scholarship. These honors combined with his extraordinary intellect facilitated offers of acceptance by MIT, Harvard, and the Juilliard School; choosing to study music, Chen earned his Bachelor's and Master's degrees at Juilliard, where he won the 2010 Gina Bachauer Piano Competition, the 2010 Munz Scholarship, and first prize at the 2008 Juilliard Concerto Competition. While attending Juilliard, Chen was the recipient of a notable third-party scholarship: the 2010 Paul and Daisy Soros Fellowship for New Americans.</p>
<p>Chen is currently pursuing his Artist Diploma at the Yale School of Music as a George W. Miles Fellowship recipient. He is studying with Hung-Kuan Chen and Tema Blackstone, and his former teachers include Jerome Lowenthal, Matti Raekallio, and Edward Francis. Chen's performances have been broadcast live on From the Top, American Public Media's Performance Today, WQXR (New York), WGBH (Boston), and WFYI (Indianapolis). The webcast of his April 2013 performance of Bartók's Piano Concerto No. 2 with the Indianapolis Symphony – which, according to International Piano, "blazed with color and excitement" – can be viewed at <a href="http://americanpianists.org/media/live">americanpianists.org</a>. 
When not at the piano, Chen enjoys tinkering with computers and composing. In the coming seasons, he will be performing under the management of the American Pianists Association, touring the U.S. and presenting recitals worldwide.</p>
</div>

<div ng-repeat="mlist in repList"><div toggle-siblings class="heading icon-right-dir hover">{{mlist.label}}</div>
<table class="repList">
	<tr ng-repeat="item in mlist.list | orderBy:'composer'">
		<td ng-bind="showComp(item.composer)"></td>
		<td>{{item.piece}}
		<a class="info" ng-repeat="file in item.pdf" ng-show="file" href="http://seanchenpiano.com/music/composing/{{file}}.pdf"><div class="small-pdf-icon"></div>{{fileOrList(item, $index)}}</a></td>
	</tr>
</table>
</div>